apiVersion: cilium.io/v2alpha1
kind: CiliumBGPClusterConfig
metadata:
  name: cilium-bgp-rack1
spec:
  nodeSelector:
    matchLabels:
      rack: rack1
  bgpInstances:
  - name: "instance-65000"
    localASN: 65005
    peers:
    - name: "peer-leaf1"
      peerASN: 65005
      peerAddress: "10.1.5.1"
      peerConfigRef:
        name: "cilium-peer"
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPClusterConfig
metadata:
  name: cilium-bgp-rack2
spec:
  nodeSelector:
    matchLabels:
      rack: rack2
  bgpInstances:
  - name: "instance-65000"
    localASN: 65008
    peers:
    - name: "peer-leaf2"
      peerASN: 65008
      peerAddress: "10.1.8.1"
      peerConfigRef:
        name: "cilium-peer"
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeerConfig
metadata:
  name: cilium-peer
spec:
  timers:
    holdTimeSeconds: 90
    keepAliveTimeSeconds: 30
  ebgpMultihop: 4
  gracefulRestart:
    enabled: true
    restartTimeSeconds: 15
  families:
    - afi: ipv4
      safi: unicast
      advertisements:
        matchLabels:
          advertise: "bgp"
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPAdvertisement
metadata:
  name: bgp-advertisements
  labels:
    advertise: bgp
spec:
  advertisements:
    - advertisementType: "PodCIDR"
      attributes:
        communities:
          standard: [ "65000:99" ]
        localPreference: 99
