apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
spec:
  replicas: 2
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
        - image: rykren/netools
          imagePullPolicy: IfNotPresent
          name: whoami
          ports:
            - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: whoami
spec:
  selector:
    app: whoami
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
