apiVersion: network.kubesphere.io/v1alpha2
kind: BgpConf
metadata:
  name: default
spec:
  as: 64512
  listenPort: 17900
  routerId: 192.168.10.11
---
apiVersion: network.kubesphere.io/v1alpha2
kind: BgpPeer
metadata:
  name: router
spec:
  conf:
    peerAs: 65000
    neighborAddress: 192.168.10.1
