apiVersion: networking.alibaba.com/v1
kind: Network
metadata:
  name: underlay-network-bgp
spec:
  nodeSelector:
    network: bgp
  type: Underlay
  mode: BGP
  netID: 65000
  config:
    bgpPeers:
      - asn: 65005
        address: 10.10.0.1
        gracefulRestartSeconds: 600

---
apiVersion: networking.alibaba.com/v1
kind: Subnet
metadata:
  name: underlay-subnet-bgp
spec:
  network: underlay-network-bgp
  range:
    version: "4"
    cidr: "69.57.56.0/24"
