apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: netools
  name: netools
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netools
  template:
    metadata:
      labels:
        app: netools
      annotations:
        "networking.alibaba.com/specified-network": "underlay-network-2"
    spec:
      containers:
      - image: rykren/nettools:latest
        name: netools
        ports:
        - containerPort: 80
      restartPolicy: Always
