---
apiVersion: networking.alibaba.com/v1
kind: Network
metadata:
  name: underlay-network
spec:
  netID: 0
  type: Underlay
  nodeSelector:
    network: "network1"

---
apiVersion: networking.alibaba.com/v1
kind: Subnet
metadata:
  name: underlay-subnet
spec:
  network: underlay-network
  netID: 0
  range:
    version: "4"
    cidr: "10.10.12.0/24"
    gateway: "10.10.12.1"
