[global.config]
  as = 65000
  router-id = "192.168.0.5"

[[neighbors]]
  [neighbors.config]
    neighbor-address = "192.168.0.2"
    peer-as = 64512

[[neighbors]]
  [neighbors.config]
    neighbor-address = "192.168.0.3"
    peer-as = 64512

[[neighbors]]
  [neighbors.config]
    neighbor-address = "192.168.0.4"
    peer-as = 64512
