kind: Cluster
name: demo
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  disableDefaultCNI: true
  podSubnet: 10.233.64.0/18
  serviceSubnet: 10.233.0.0/18
nodes:
  - role: control-plane
    extraPortMappings:
    - containerPort: 30880
      hostPort: 30880
      listenAddress: "0.0.0.0"
      protocol: tcp
    - containerPort: 30881
      hostPort: 30881
      listenAddress: "0.0.0.0"
      protocol: tcp
    image: kindest/node:v1.24.17
  - role: worker
    image: kindest/node:v1.24.17
