kind: Cluster
name: demo
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  disableDefaultCNI: true
  podSubnet: 10.233.64.0/18
  serviceSubnet: 10.233.0.0/18
nodes:
  - role: control-plane
    image: kindest/node:v1.27.10
  - role: worker
    image: kindest/node:v1.27.10
  - role: worker
    image: kindest/node:v1.27.10
