apiVersion: spiderpool.spidernet.io/v2beta1
kind: SpiderIPPool
metadata:
  name: vlan100-v4
spec:
  default: false
  ips:
  - "172.100.1.2-172.100.1.240"
  subnet: 172.100.0.0/16
  gateway: 172.100.0.1
  multusName:
  - kube-system/macvlan-vlan100
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
spec:
  replicas: 2
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      annotations:
        ipam.spidernet.io/ippool: |-
          {
            "ipv4": ["vlan100-v4"]
          }
      labels:
        app: whoami
    spec:
      containers:
      - name: whoami
        image: rykren/whoami
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
